### ISSUE TITLE
IndexError when exporting to IMX500 through Ultralytics Yolov8

### ISSUE THREAD

**Issue by JaimyvS** [sony/model_optimization#1288]
### Issue Type

Bug

### Source

pip (model-compression-toolkit)

### MCT Version

2.1.1

### OS Platform and Distribution

Linux Ubuntu 24.04.1 LTS

### Python version

3.11.10

### Describe the issue

I've been trying to export a custom trained Yolov8 classification model using Ultralytics own export function to the IMX500 format for use with the Raspberry Pi AI camera, but every time it finishes with a ```IndexError: index 1 is out of bounds for dimension 0 with size 1``` Even when trying to export the base Yolov8n-cls.pt model. Exporting to another format, for example ONNX, does finish succesfully.

### Expected behaviour

Succesful IMX500 export.

### Code to reproduce the issue

```python
yolo export model=runs/classify/train8/weights/best.pt format=imx imgsz=224 data=/home/jaimy/projects/pokemon/training_sets/training_set_v3/ device=0

yolo export model=yolov8n-cls.pt format=imx
```

### Log output

When running ```yolo export model=runs/classify/train8/weights/best.pt format=imx imgsz=224 data=/home/jaimy/projects/pokemon/training_sets/training_set_v3/ device=0``` on my custom model:
```
Ultralytics 8.3.37 🚀 Python-3.11.10 torch-2.5.1 CUDA:0 (NVIDIA GeForce RTX 4080 SUPER, 16050MiB)
WARNING ⚠️ IMX only supports int8 export, setting int8=True.
YOLOv8n-cls summary (fused): 73 layers, 1,628,311 parameters, 0 gradients, 3.4 GFLOPs

PyTorch: starting from 'runs/classify/train8/weights/best.pt' with input shape (1, 3, 224, 224) BCHW and output shape(s) (1, 151) (3.2 MB)
/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/sony_custom_layers/pytorch/object_detection/nms.py:120: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract(MULTICLASS_NMS_TORCH_OP_QUALNAME)
IMX: collecting INT8 calibration images from 'data=/home/jaimy/projects/pokemon/training_sets/training_set_v3/'
train: /home/jaimy/projects/pokemon/training_sets/training_set_v3/train... found 7398 images in 151 classes ✅ 
val: /home/jaimy/projects/pokemon/training_sets/training_set_v3/val... found 1662 images in 151 classes ✅ 
test: /home/jaimy/projects/pokemon/training_sets/training_set_v3/test... found 1682 images in 151 classes ✅ 
Scanning /home/jaimy/projects/pokemon/training_sets/training_set_v3/val/Abra.cache... 0 images, 1662 backgrounds, 0 corrupt: 100%|██████████| 1662/1662 [00:00<?, ?it/s]
WARNING ⚠️ No labels found in /home/jaimy/projects/pokemon/training_sets/training_set_v3/val/Abra.cache, training may not work correctly. See https://docs.ultralytics.com/datasets for dataset formatting guidance.
representative_data_gen generates a batch size of 1 which can be slow for optimization: consider increasing the batch size
representative_data_gen generates a batch size of 1 which can be slow for optimization: consider increasing the batch size
ERROR:Model Compression Toolkit:Found duplicate qco types!
ERROR:Model Compression Toolkit:Found duplicate qco types!
ERROR:Model Compression Toolkit:Found duplicate qco types!
ERROR:Model Compression Toolkit:Found duplicate qco types!
ERROR:Model Compression Toolkit:Found duplicate qco types!
ERROR:Model Compression Toolkit:Found duplicate qco types!
ERROR:Model Compression Toolkit:Found duplicate qco types!
ERROR:Model Compression Toolkit:Found duplicate qco types!
ERROR:Model Compression Toolkit:Found duplicate qco types!
ERROR:Model Compression Toolkit:Found duplicate qco types!
ERROR:Model Compression Toolkit:Found duplicate qco types!
ERROR:Model Compression Toolkit:Found duplicate qco types!
Statistics Collection: 1662it [00:31, 51.99it/s]

Running quantization parameters search. This process might take some time, depending on the model size and the selected quantization methods.

Calculating quantization parameters: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 80/80 [00:04<00:00, 17.27it/s]

Please run your accuracy evaluation on the exported quantized model to verify it's accuracy.
Checkout the FAQ and Troubleshooting pages for resolving common issues and improving the quantized model accuracy:
FAQ: https://github.com/sony/model_optimization/tree/main/FAQ.md
Quantization Troubleshooting: https://github.com/sony/model_optimization/tree/main/quantization_troubleshooting.md
Exporting onnx model with MCTQ quantizers: runs/classify/train8/weights/best_imx_model/runs/classify/train8/weights/best_imx.onnx
IMX: export failure ❌ 41.9s: index 1 is out of bounds for dimension 0 with size 1
Traceback (most recent call last):
  File "/home/jaimy/anaconda3/envs/pt-converter/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
             ^^^^^^^^^^^^
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/ultralytics/cfg/__init__.py", line 969, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/ultralytics/engine/model.py", line 734, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/ultralytics/engine/exporter.py", line 381, in __call__
    f[13], _ = self.export_imx()
               ^^^^^^^^^^^^^^^^^
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/ultralytics/engine/exporter.py", line 146, in outer_func
    raise e
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/ultralytics/engine/exporter.py", line 141, in outer_func
    f, model = inner_func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/ultralytics/engine/exporter.py", line 1211, in export_imx
    mct.exporter.pytorch_export_model(
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/model_compression_toolkit/exporter/model_exporter/pytorch/pytorch_export_facade.py", line 102, in pytorch_export_model
    exporter.export()
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/model_compression_toolkit/exporter/model_exporter/pytorch/fakely_quant_onnx_pytorch_exporter.py", line 109, in export
    torch.onnx.export(self.model,
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/torch/onnx/__init__.py", line 375, in export
    export(
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/torch/onnx/utils.py", line 502, in export
    _export(
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/torch/onnx/utils.py", line 1564, in _export
    graph, params_dict, torch_out = _model_to_graph(
                                    ^^^^^^^^^^^^^^^^
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/torch/onnx/utils.py", line 1113, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/torch/onnx/utils.py", line 997, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/torch/onnx/utils.py", line 904, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/torch/jit/_trace.py", line 1500, in _get_trace_graph
    outs = ONNXTracedModule(
           ^^^^^^^^^^^^^^^^^
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/torch/jit/_trace.py", line 139, in forward
    graph, out = torch._C._create_graph_by_tracing(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/torch/jit/_trace.py", line 130, in wrapper
    outs.append(self.inner(*trace_inputs))
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1726, in _slow_forward
    result = self.forward(*input, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/ultralytics/engine/exporter.py", line 1191, in forward
    scores = outputs[1]
             ~~~~~~~^^^
IndexError: index 1 is out of bounds for dimension 0 with size 1
```

When running ```yolo export model=yolov8n-cls.pt format=imx``` on the base yolo classification model:
```
Ultralytics 8.3.37 🚀 Python-3.11.10 torch-2.5.1 CPU (AMD Ryzen 7 7800X3D 8-Core Processor)
WARNING ⚠️ IMX only supports int8 export, setting int8=True.
WARNING ⚠️ INT8 export requires a missing 'data' arg for calibration. Using default 'data=imagenet10'.
YOLOv8n-cls summary (fused): 73 layers, 2,715,880 parameters, 0 gradients, 4.3 GFLOPs

PyTorch: starting from 'yolov8n-cls.pt' with input shape (1, 3, 224, 224) BCHW and output shape(s) (1, 1000) (5.3 MB)
/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/sony_custom_layers/pytorch/object_detection/nms.py:120: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract(MULTICLASS_NMS_TORCH_OP_QUALNAME)
IMX: collecting INT8 calibration images from 'data=imagenet10'
train: /home/jaimy/projects/pokemon/pt-converter/datasets/imagenet10/train... found 12 images in 10 classes ✅ 
val: /home/jaimy/projects/pokemon/pt-converter/datasets/imagenet10/val... found 12 images in 10 classes ✅ 
test: None...
Scanning /home/jaimy/projects/pokemon/pt-converter/datasets/imagenet10/val/n01440764.cache... 0 images, 12 backgrounds, 0 corrupt: 100%|██████████| 12/12 [00:00<?, ?it/s]
WARNING ⚠️ No labels found in /home/jaimy/projects/pokemon/pt-converter/datasets/imagenet10/val/n01440764.cache, training may not work correctly. See https://docs.ultralytics.com/datasets for dataset formatting guidance.
IMX: WARNING ⚠️ >300 images recommended for INT8 calibration, found 12 images.
representative_data_gen generates a batch size of 1 which can be slow for optimization: consider increasing the batch size
representative_data_gen generates a batch size of 1 which can be slow for optimization: consider increasing the batch size
ERROR:Model Compression Toolkit:Found duplicate qco types!
ERROR:Model Compression Toolkit:Found duplicate qco types!
ERROR:Model Compression Toolkit:Found duplicate qco types!
ERROR:Model Compression Toolkit:Found duplicate qco types!
ERROR:Model Compression Toolkit:Found duplicate qco types!
ERROR:Model Compression Toolkit:Found duplicate qco types!
Mixed precision enabled.
ERROR:Model Compression Toolkit:Found duplicate qco types!
ERROR:Model Compression Toolkit:Found duplicate qco types!
ERROR:Model Compression Toolkit:Found duplicate qco types!
ERROR:Model Compression Toolkit:Found duplicate qco types!
ERROR:Model Compression Toolkit:Found duplicate qco types!
ERROR:Model Compression Toolkit:Found duplicate qco types!
Statistics Collection: 12it [00:00, 54.30it/s]

Running quantization parameters search. This process might take some time, depending on the model size and the selected quantization methods.

Calculating quantization parameters: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 80/80 [00:18<00:00,  4.40it/s]
Starting to evaluate metrics
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 27/27 [00:03<00:00,  8.95it/s]
Welcome to the CBC MILP Solver 
Version: 2.10.3 
Build Date: Dec 15 2019 

command line - /home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/pulp/solverdir/cbc/linux/64/cbc /tmp/985e69e327674a898ee37e02af4f7679-pulp.mps -sec 60 -timeMode elapsed -branch -printingOptions all -solution /tmp/985e69e327674a898ee37e02af4f7679-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 60 COLUMNS
At line 493 RHS
At line 549 BOUNDS
At line 631 ENDATA
Problem MODEL has 55 rows, 108 columns and 243 elements
Coin0008I MODEL read with 0 errors
seconds was changed from 1e+100 to 60
Option for timeMode changed from cpu to elapsed
Continuous objective value is 2.97337 - 0.00 seconds
Cgl0003I 0 fixed, 0 tightened bounds, 1 strengthened rows, 0 substitutions
Cgl0004I processed model has 28 rows, 81 columns (81 integer (81 of which binary)) and 136 elements
Cbc0038I Initial state - 2 integers unsatisfied sum - 0.871582
Cbc0038I Pass   1: suminf.    0.82243 (2) obj. 3.27828 iterations 1
Cbc0038I Solution found of 3.80768
Cbc0038I Before mini branch and bound, 78 integers at bound fixed and 0 continuous
Cbc0038I Full problem 28 rows 81 columns, reduced to 0 rows 0 columns
Cbc0038I Mini branch and bound improved solution from 3.80768 to 3.05733 (0.00 seconds)
Cbc0038I Round again with cutoff of 3.04892
Cbc0038I Reduced cost fixing fixed 45 variables on major pass 2
Cbc0038I Pass   2: suminf.    0.87158 (2) obj. 2.97337 iterations 2
Cbc0038I Pass   3: suminf.    0.11296 (2) obj. 3.04892 iterations 19
Cbc0038I Pass   4: suminf.    0.11296 (2) obj. 3.04892 iterations 0
Cbc0038I Pass   5: suminf.    0.11296 (2) obj. 3.04892 iterations 0
Cbc0038I Pass   6: suminf.    0.11296 (2) obj. 3.04892 iterations 1
Cbc0038I Pass   7: suminf.    0.11296 (2) obj. 3.04892 iterations 0
Cbc0038I Pass   8: suminf.    0.98678 (2) obj. 2.98195 iterations 1
Cbc0038I Pass   9: suminf.    0.83566 (4) obj. 3.04892 iterations 4
Cbc0038I Pass  10: suminf.    0.83566 (4) obj. 3.04892 iterations 0
Cbc0038I Pass  11: suminf.    0.46532 (2) obj. 3.04892 iterations 2
Cbc0038I Pass  12: suminf.    0.79958 (2) obj. 2.99423 iterations 1
Cbc0038I Pass  13: suminf.    0.79958 (2) obj. 2.99423 iterations 0
Cbc0038I Pass  14: suminf.    0.79958 (2) obj. 2.99423 iterations 0
Cbc0038I Pass  15: suminf.    0.78518 (2) obj. 3.04845 iterations 3
Cbc0038I Pass  16: suminf.    0.78518 (2) obj. 3.04845 iterations 0
Cbc0038I Pass  17: suminf.    0.79160 (2) obj. 3.04892 iterations 1
Cbc0038I Pass  18: suminf.    0.79160 (2) obj. 3.04892 iterations 0
Cbc0038I Pass  19: suminf.    0.79160 (2) obj. 3.04892 iterations 0
Cbc0038I Pass  20: suminf.    0.27119 (2) obj. 3.04892 iterations 1
Cbc0038I Pass  21: suminf.    0.27119 (2) obj. 3.04892 iterations 0
Cbc0038I Pass  22: suminf.    0.81398 (2) obj. 2.98086 iterations 1
Cbc0038I Pass  23: suminf.    0.79958 (2) obj. 3.00099 iterations 1
Cbc0038I Pass  24: suminf.    0.79958 (2) obj. 3.00099 iterations 0
Cbc0038I Pass  25: suminf.    0.55620 (2) obj. 3.04892 iterations 1
Cbc0038I Pass  26: suminf.    0.55620 (2) obj. 3.04892 iterations 1
Cbc0038I Pass  27: suminf.    0.55620 (2) obj. 3.04892 iterations 0
Cbc0038I Pass  28: suminf.    0.81398 (2) obj. 3.00207 iterations 1
Cbc0038I Pass  29: suminf.    1.13132 (4) obj. 3.04892 iterations 1
Cbc0038I Pass  30: suminf.    1.13132 (4) obj. 3.04892 iterations 0
Cbc0038I Pass  31: suminf.    1.13132 (4) obj. 3.04892 iterations 0
Cbc0038I No solution found this major pass
Cbc0038I Before mini branch and bound, 65 integers at bound fixed and 0 continuous
Cbc0038I Mini branch and bound did not improve solution (0.00 seconds)
Cbc0038I After 0.00 seconds - Feasibility pump exiting with objective of 3.05733 - took 0.00 seconds
Cbc0012I Integer solution of 3.0573278 found by feasibility pump after 0 iterations and 0 nodes (0.00 seconds)
Cbc0006I The LP relaxation is infeasible or too expensive
Cbc0013I At root node, 0 cuts changed objective from 2.9733748 to 3.0573276 in 1 passes
Cbc0014I Cut generator 0 (Probing) - 12 row cuts average 8.0 elements, 1 column cuts (1 active)  in 0.000 seconds - new frequency is 1
Cbc0014I Cut generator 1 (Gomory) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 2 (Knapsack) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 3 (Clique) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 4 (MixedIntegerRounding2) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 5 (FlowCover) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 7 (ZeroHalf) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0001I Search completed - best objective 3.057327829806601, took 0 iterations and 0 nodes (0.00 seconds)
Cbc0035I Maximum depth 0, 44 variables fixed on reduced cost
Cuts at root node changed objective from 2.97337 to 3.05733
Probing was tried 1 times and created 13 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                3.05732783
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Optimal
Final weights bit-width configuration: [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 4, 8, 8, 4, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 4]

Please run your accuracy evaluation on the exported quantized model to verify it's accuracy.
Checkout the FAQ and Troubleshooting pages for resolving common issues and improving the quantized model accuracy:
FAQ: https://github.com/sony/model_optimization/tree/main/FAQ.md
Quantization Troubleshooting: https://github.com/sony/model_optimization/tree/main/quantization_troubleshooting.md
Exporting onnx model with MCTQ quantizers: yolov8n-cls_imx_model/yolov8n-cls_imx.onnx
IMX: export failure ❌ 23.7s: index 1 is out of bounds for dimension 0 with size 1
Traceback (most recent call last):
  File "/home/jaimy/anaconda3/envs/pt-converter/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
             ^^^^^^^^^^^^
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/ultralytics/cfg/__init__.py", line 969, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/ultralytics/engine/model.py", line 734, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/ultralytics/engine/exporter.py", line 381, in __call__
    f[13], _ = self.export_imx()
               ^^^^^^^^^^^^^^^^^
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/ultralytics/engine/exporter.py", line 146, in outer_func
    raise e
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/ultralytics/engine/exporter.py", line 141, in outer_func
    f, model = inner_func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/ultralytics/engine/exporter.py", line 1211, in export_imx
    mct.exporter.pytorch_export_model(
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/model_compression_toolkit/exporter/model_exporter/pytorch/pytorch_export_facade.py", line 102, in pytorch_export_model
    exporter.export()
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/model_compression_toolkit/exporter/model_exporter/pytorch/fakely_quant_onnx_pytorch_exporter.py", line 109, in export
    torch.onnx.export(self.model,
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/torch/onnx/__init__.py", line 375, in export
    export(
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/torch/onnx/utils.py", line 502, in export
    _export(
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/torch/onnx/utils.py", line 1564, in _export
    graph, params_dict, torch_out = _model_to_graph(
                                    ^^^^^^^^^^^^^^^^
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/torch/onnx/utils.py", line 1113, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/torch/onnx/utils.py", line 997, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/torch/onnx/utils.py", line 904, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/torch/jit/_trace.py", line 1500, in _get_trace_graph
    outs = ONNXTracedModule(
           ^^^^^^^^^^^^^^^^^
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/torch/jit/_trace.py", line 139, in forward
    graph, out = torch._C._create_graph_by_tracing(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/torch/jit/_trace.py", line 130, in wrapper
    outs.append(self.inner(*trace_inputs))
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1726, in _slow_forward
    result = self.forward(*input, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaimy/anaconda3/envs/pt-converter/lib/python3.11/site-packages/ultralytics/engine/exporter.py", line 1191, in forward
    scores = outputs[1]
             ~~~~~~~^^^
IndexError: index 1 is out of bounds for dimension 0 with size 1
```

**Comment by ServiAmirPM** [comment]
Hi @JaimyvS 
Thanks for posting this issue. At the moment the Ultralytics integration is only for object detection for yolov8n.
We hope to deepen the integration by community contribution to Ultralytics package, as well as technical work to be done by the teams.
