### ISSUE TITLE
wrong message when call mct.get_target_platform_capabilities('tensorflow', 'default') without tensorflow_model_optimization

### ISSUE THREAD

**Issue by k-ymd** [sony/model_optimization#223]
### Issue Type

Bug

### Source

source

### MCT Version

1.4.0

### OS Platform and Distribution

Ubuntu 18.04

### Python version

3.8.6

### Describe the issue

```shell
When I tried example_keras_mobilenet.py, I got below error message.

This sample code is correct, but I can't run it.
I debugged it and it was due to the fact that tensorflow_model_optimization was not installed.
When I installed it, it worked.

Could you please show an error message indicating that it is not installed.

BTW, the command to get MCT version in MCT Issue Template is wrong.
Isn't the module name model_compression_toolkit, not model-compression-toolkit. Right?
```

### Expected behaviour

```shell
https://github.com/sony/model_optimization/blob/c414024da063e56845331f45ee1488b90988984c/model_compression_toolkit/tpc_models/get_target_platform_capabilities.py#L26

I think this condition isn't enough.
```

### Code to reproduce the issue

```shell
mct.get_target_platform_capabilities('tensorflow', 'default')
```

### Log output
```
(mct) yamada@Sirius:~/playground/MCT/model_optimization/tutorials$ python example_keras_mobilenet.py
Starting Scanning Disk: /data/image/imagenet/val
Finished Disk Scanning: Found 50000 files
Traceback (most recent call last):
  File "example_keras_mobilenet.py", line 81, in <module>
    target_platform_cap = mct.get_target_platform_capabilities('tensorflow', 'default')
  File "/home/yamada/playground/MCT/mct/lib/python3.8/site-packages/model_compression_toolkit-1.4.0-py3.8.egg/model_compression_toolkit/tpc_models/get_target_platform_capabilities.py", line 78, in get_target_platform_capabilities
AssertionError: Target platform model named default is not supported for framework tensorflow
```

**Comment by reuvenperetz** [comment]
Hi!
Thank you for drawing our attention to this. A fix has been merged. You can try it using mct-nightly.
Please let us know about any other issues you're facing.

Thanks!
