### ISSUE TITLE
MCT for yolov5n.pt

### ISSUE THREAD

**Issue by YoshikiKato0220** [sony/model_optimization#674]
### Issue Type

Feature Request

### Source

pip (model-compression-toolkit)

### MCT Version

1.8.0

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.8

### Describe the issue

```shell
I tried to use MCT for yolov5n.
I changed tutorials/example_pytorch_mobilenet_v2.py for yolov5n.
I ran changed script and got error messages as follows, 
in pytorch_post_training_quantization_experimental,

torch.fx.proxy.TraceError: symbolically traced variables cannot be used as inputs to control flow
```

### Expected behaviour

```shell
pytorch_post_training_quantization_experimental pass normally.

But is this limitation of pytorch?
https://pytorch.org/docs/stable/fx.html#limitations-of-symbolic-tracing

if statements where the condition may depend on the input values of the program
↓
  File "/usr/src/app/models/yolo.py", line 207, in forward
    if augment:
```

### Code to reproduce the issue

```shell
[in host]
docker pull ultralytics/yolov5
docker run --name yolov5n -it --gpus all ultralytics/yolov5:latest /bin/bash

https://github.com/ultralytics/yolov5/releases/download/v7.0/yolov5n.pt
copy yolov5n.pt to container's /usr/src/app
copy example_pytorch_yolov5n.py to container’s /usr/src/app/

[in container]
pip install model-compression-toolkit
cd /usr/src/app
python example_pytorch_yolov5n.py --representative_dataset_dir ./rep_dataset --batch_size 2 

[a minimal snippet of example_pytorch_yolov5n.py]
# from https://github.com/ultralytics/yolov5/export.py
model = Ensemble()
ckpt = torch.load('./yolov5n.pt', map_location='cpu')
model.append(ckpt.fuse().eval() if fuse and hasattr(ckpt, 'fuse') else ckpt.eval())

    core_config = mct.CoreConfig(quantization_config=mct.QuantizationConfig(z_threshold=args.z_threshold))

    quantized_model, quantization_info = mct.ptq.pytorch.quantization_facade.pytorch_post_training_quantization_experimental(
        in_module=model,
        representative_data_gen=representative_data_gen,
        core_config=core_config,
        target_platform_capabilities=target_platform_cap
    )
```

### Log output

```shell
cd /usr/src/app
python example_pytorch_yolov5n.py --representative_dataset_dir ./rep_dataset --batch_size 2 

Starting Scanning Disk: ./rep_dataset
Finished Disk Scanning: Found 2 files
YOLOv5 ? v7.0-63-gcdd804d Python-3.8.10 torch-1.13.1+cu117 CPU

Fusing layers...
YOLOv5n summary: 213 layers, 1867405 parameters, 0 gradients
Traceback (most recent call last):
  File "example_pytorch_yolov5n.py", line 235, in <module>
    export(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "example_pytorch_yolov5n.py", line 224, in export
    quantized_model, quantization_info = mct.ptq.pytorch.quantization_facade.pytorch_post_training_quantization_experimental(
  File "/usr/local/lib/python3.8/dist-packages/model_compression_toolkit/ptq/pytorch/quantization_facade.py", line 109, in pytorch_post_training_quantization_experimental
    tg, bit_widths_config = core_runner(in_model=in_module,
  File "/usr/local/lib/python3.8/dist-packages/model_compression_toolkit/core/runner.py", line 92, in core_runner
    graph = read_model_to_graph(in_model,
File "/usr/local/lib/python3.8/dist-packages/model_compression_toolkit/core/runner.py", line 288, in read_model_to_graph
    graph = fw_impl.model_reader(in_model,
  File "/usr/local/lib/python3.8/dist-packages/model_compression_toolkit/core/pytorch/pytorch_implementation.py", line 130, in model_reader
    return model_reader(module, representative_data_gen, self.to_numpy, self.to_tensor)
  File "/usr/local/lib/python3.8/dist-packages/model_compression_toolkit/core/pytorch/reader/reader.py", line 147, in model_reader
    fx_model = fx_graph_module_generation(model, representative_data_gen, to_tensor)
  File "/usr/local/lib/python3.8/dist-packages/model_compression_toolkit/core/pytorch/reader/reader.py", line 87, in fx_graph_module_generation
    symbolic_traced = symbolic_trace(pytorch_model)
  File "/usr/local/lib/python3.8/dist-packages/torch/fx/_symbolic_trace.py", line 1070, in symbolic_trace
    graph = tracer.trace(root, concrete_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/fx/_symbolic_trace.py", line 739, in trace
    (self.create_arg(fn(*args)),),
  File "/usr/src/app/models/yolo.py", line 207, in forward
    if augment:
  File "/usr/local/lib/python3.8/dist-packages/torch/fx/proxy.py", line 298, in __bool__
    return self.tracer.to_bool(self)
  File "/usr/local/lib/python3.8/dist-packages/torch/fx/proxy.py", line 174, in to_bool
    raise TraceError('symbolically traced variables cannot be used as inputs to control flow')
torch.fx.proxy.TraceError: symbolically traced variables cannot be used as inputs to control flow
```

**Comment by Idan-BenAmi** [comment]
Hi,
Thank you for bringing this issue to our attention. We appreciate your support.
Upon reviewing the issue, we have identified that the problem is caused by the limitations of an external library that our project relies on: "torch.fx".
The FX toolkit helps us to acquire a static graph representation from the PyTorch models which is essential for performing model compression manipulation like batch norm folding, for instance.

We are currently in the process of creating a tutorial that showcases how to utilize MCT with object detection models (such as YOLO). Once this tutorial is completed, we will notify you.
If you have any further questions, please feel free to reach out.
Regards
Idan

**Comment by Idan-BenAmi** [comment]
Hi, 
The tutorial is available here: https://github.com/sony/model_optimization/tree/main/tutorials/quick_start
Best regards
Idan
