### ISSUE TITLE
MCT for yolox_tiny.pth

### ISSUE THREAD

**Issue by YoshikiKato0220** [sony/model_optimization#676]
### Issue Type

Feature Request

### Source

pip (model-compression-toolkit)

### MCT Version

1.8.0

### OS Platform and Distribution

Linux Ubuntu 18.04

### Python version

3.10

### Describe the issue

```shell
I tried to use MCT for yolox-tiny.
I changed tutorials/example_pytorch_mobilenet_v2.py for yolox-tiny.
I ran changed script and got error messages as follows,
in pytorch_post_training_quantization_experimental,
TypeError: arange(): argument 'end' (position 1) must be Number, not Proxy
```

### Expected behaviour

```shell
pytorch_post_training_quantization_experimental pass normally.

But is this limitation of pytorch?
https://pytorch.org/docs/stable/fx.html#torch.fx.Proxy

Proxy objects cannot be iterated. In other words, the symbolic tracer will throw an error if a Proxy is used in a loop or as an *args/**kwargs function argument.
↓
File "/workspace/YOLOX/yolox/models/yolo_head.py", line 239, in decode_outputs
for (hsize, wsize), stride in zip(self.hw, self.strides):
    yv, xv = meshgrid([torch.arange(hsize), torch.arange(wsize)])
```

### Code to reproduce the issue

```shell
[in host]
docker pull pytorch/pytorch:1.13.1-cuda11.6-cudnn8-devel
docker run --name yolox -it --gpus all pytorch/pytorch:1.13.1-cuda11.6-cudnn8-devel /bin/bash

https://github.com/Megvii-BaseDetection/YOLOX/releases/download/0.1.1rc0/yolox_tiny.pth
copy yolox_tiny.pth to container's /workspace/YOLOX/
copy example_pytorch_yolox.py to container’s /workspace/YOLOX/

[in container]
cd /workspace
apt update
apt install -y git libgl1-mesa-glx libglib2.0-0 libsm6 libxrender1 libxext6
git clone https://github.com/Megvii-BaseDetection/YOLOX
cd YOLOX
pip3 install -v -e .
python example_pytorch_yolox.py --representative_dataset_dir ./rep_dataset --batch_size 2

[a minimal snippet of example_pytorch_yolox.py]
    exp = get_exp(None, 'yolox-tiny')
    model = exp.get_model()
    ckpt = torch.load('./yolox_tiny.pth', map_location="cpu")
    model.load_state_dict(ckpt["model"])

    core_config = mct.CoreConfig(quantization_config=mct.QuantizationConfig(z_threshold=args.z_threshold))

    quantized_model, quantization_info = mct.ptq.pytorch.quantization_facade.pytorch_post_training_quantization_experimental(
        in_module=model,
        representative_data_gen=representative_data_gen,
        core_config=core_config,
        target_platform_capabilities=target_platform_cap
    )
```

### Log output

```shell
Starting Scanning Disk: ./rep_dataset
Finished Disk Scanning: Found 2 files
Traceback (most recent call last):
  File "/workspace/YOLOX/example_pytorch_yolox.py", line 169, in <module>
    export(args)
  File "/workspace/YOLOX/example_pytorch_yolox.py", line 158, in export
    quantized_model, quantization_info = mct.ptq.pytorch.quantization_facade.pytorch_post_training_quantization_experimental(
  File "/opt/conda/lib/python3.10/site-packages/model_compression_toolkit/ptq/pytorch/quantization_facade.py", line 109, in pytorch_post_training_quantization_experimental
    tg, bit_widths_config = core_runner(in_model=in_module,
  File "/opt/conda/lib/python3.10/site-packages/model_compression_toolkit/core/runner.py", line 92, in core_runner
    graph = read_model_to_graph(in_model,
  File "/opt/conda/lib/python3.10/site-packages/model_compression_toolkit/core/runner.py", line 288, in read_model_to_graph
    graph = fw_impl.model_reader(in_model,
  File "/opt/conda/lib/python3.10/site-packages/model_compression_toolkit/core/pytorch/pytorch_implementation.py", line 130, in model_reader
    return model_reader(module, representative_data_gen, self.to_numpy, self.to_tensor)
   File "/opt/conda/lib/python3.10/site-packages/model_compression_toolkit/core/pytorch/reader/reader.py", line 147, in model_reader
    fx_model = fx_graph_module_generation(model, representative_data_gen, to_tensor)
  File "/opt/conda/lib/python3.10/site-packages/model_compression_toolkit/core/pytorch/reader/reader.py", line 87, in fx_graph_module_generation
    symbolic_traced = symbolic_trace(pytorch_model)
  File "/opt/conda/lib/python3.10/site-packages/torch/fx/_symbolic_trace.py", line 1070, in symbolic_trace
    graph = tracer.trace(root, concrete_args)
  File "/opt/conda/lib/python3.10/site-packages/torch/fx/_symbolic_trace.py", line 739, in trace
    (self.create_arg(fn(*args)),),
  File "/workspace/YOLOX/yolox/models/yolox.py", line 46, in forward
    outputs = self.head(fpn_outs)
  File "/opt/conda/lib/python3.10/site-packages/torch/fx/_symbolic_trace.py", line 717, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/fx/_symbolic_trace.py", line 434, in call_module
    return forward(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/fx/_symbolic_trace.py", line 710, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/YOLOX/yolox/models/yolo_head.py", line 211, in forward
    return self.decode_outputs(outputs, dtype=xin[0].type())
  File "/workspace/YOLOX/yolox/models/yolo_head.py", line 239, in decode_outputs
    yv, xv = meshgrid([torch.arange(hsize), torch.arange(wsize)])
TypeError: arange(): argument 'end' (position 1) must be Number, not Proxy
```

**Comment by Idan-BenAmi** [comment]
Hi,
Thank you for bringing this issue to our attention. We appreciate your support.
We have identified that the problem you encountered is due to the same limitations mentioned in the previous issue you reported: "MCT for yolov5n.pt". These limitations are associated with an external library that our project relies on: "torch.fx".

We are currently in the process of creating a tutorial that showcases how to utilize MCT with object detection models (such as YOLO). Once this tutorial is completed, we will notify you.
If you have any further questions, please feel free to reach out.
Regards
Idan
