### ISSUE TITLE
MCT for yolov5n in Saved model format

### ISSUE THREAD

**Issue by YoshikiKato0220** [sony/model_optimization#677]
### Issue Type

Feature Request

### Source

pip (model-compression-toolkit)

### MCT Version

1.8.0

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.8

### Describe the issue

```shell
I tried to use MCT for yolov5n in Saved model format.
I changed tutorials/example_keras_mobilenet.py for yolov5n.
I ran changed script and got error messages as follows,
in keras_post_training_quantization_experimental,
[data_format = layer.get_config().get(CHANNELS_FORMAT) in get_config raise NotImplementedError]

I added get_config method for custom layer like
https://stackoverflow.com/questions/63476635/notimplementederror-layer-attention-has-arguments-in-init-and-therefore-m

I could erase NotImplementedError, but now 
[TypeError: (‘Keyword argument not understood:’, ‘conv‘)] has occurred
in [node_instance = _layer_class.from_config(framework_attr)
instance_builder.py ]
```

### Expected behaviour

```shell
keras_post_training_quantization_experimental pass normally.
But is this error derived from custom layer?

I read https://github.com/sony/model_optimization/issues/428
[MCT doesn't support custom layers. In general, custom layers can be problematic to quantize because MCT may unfamiliar with custom layer operations. We encourage you to implement these layer as part of your model. Anyway we will consider supporting custom layers in the future.]
```

### Code to reproduce the issue

```shell
[in host]
docker pull ultralytics/yolov5
docker run --name yolov5n -it --gpus all ultralytics/yolov5:latest /bin/bash
https://github.com/ultralytics/yolov5/releases/download/v7.0/yolov5n.pt
copy yolov5n.pt to container's /usr/src/app
copy example_keras_yolov5n.py to container’s /usr/src/app/

[in container]
pip install model-compression-toolkit
pip install tensorflow-model-optimization
pip install tensorflow-cpu==2.9.0
python export.py --include=tflite --weights=yolov5n.pt --keras --int8 --imgsz 320
python example_keras_yolov5n.py --representative_dataset_dir ./rep_dataset 

[a minimal snippet of example_keras_yolov5n.py]
    model = keras.models.load_model('./yolov5n_saved_model')
    quantized_model, quantization_info = mct.ptq.keras.quantization_facade.keras_post_training_quantization_experimental(model, representative_data_gen, target_platform_capabilities=target_platform_cap)
```

### Log output

```shell
Starting Scanning Disk: ./rep_dataset
Finished Disk Scanning: Found 2 files
WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.
Traceback (most recent call last):
  File "example_keras_yolov5n.py", line 118, in <module>
    quantized_model, quantization_info = mct.ptq.keras.quantization_facade.keras_post_training_quantization_experimental(model,
  File "/usr/local/lib/python3.8/dist-packages/model_compression_toolkit/ptq/keras/quantization_facade.py", line 138, in keras_post_training_quantization_experimental
    tg, bit_widths_config = core_runner(in_model=in_model,
  File "/usr/local/lib/python3.8/dist-packages/model_compression_toolkit/core/runner.py", line 98, in core_runner
    tg = _prepare_model_for_quantization(graph,
  File "/usr/local/lib/python3.8/dist-packages/model_compression_toolkit/core/runner.py", line 347, in _prepare_model_for_quantization
    mi = ModelCollector(transformed_graph,
  File "/usr/local/lib/python3.8/dist-packages/model_compression_toolkit/core/common/model_collector.py", line 78, in __init__
    self.model, _ = self.fw_impl.model_builder(self.graph,
  File "/usr/local/lib/python3.8/dist-packages/model_compression_toolkit/core/keras/keras_implementation.py", line 167, in model_builder
    return keras_model_builder(graph=graph,
  File "/usr/local/lib/python3.8/dist-packages/model_compression_toolkit/core/keras/back2framework/float_model_builder.py", line 43, in __init__
    super().__init__(graph,
  File "/usr/local/lib/python3.8/dist-packages/model_compression_toolkit/core/keras/back2framework/keras_model_builder.py", line 115, in __init__
    self.oh = OperationHandler(self.graph)
  File "/usr/local/lib/python3.8/dist-packages/model_compression_toolkit/core/keras/back2framework/instance_builder.py", line 41, in __init__
    self.node_to_fw_op_dict = instance_builder(self.node_sort)
  File "/usr/local/lib/python3.8/dist-packages/model_compression_toolkit/core/keras/back2framework/instance_builder.py", line 108, in instance_builder
    keras_node = node_builder(n)
  File "/usr/local/lib/python3.8/dist-packages/model_compression_toolkit/core/keras/back2framework/instance_builder.py", line 84, in node_builder
    node_instance = _layer_class.from_config(framework_attr)  # Build layer from node's configuration.
  File "/usr/local/lib/python3.8/dist-packages/keras/engine/base_layer.py", line 783, in from_config
    return cls(**config)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/training/tracking/base.py", line 587, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/keras/engine/base_layer.py", line 332, in __init__
    generic_utils.validate_kwargs(kwargs, allowed_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/generic_utils.py", line 1174, in validate_kwargs
    raise TypeError(error_message, kwarg)
TypeError: ('Keyword argument not understood:', 'conv')
```

**Comment by eladc-git** [comment]
Hi,
Thank you for using MCT.
The error you got is probably because of custom objects that Keras can not serialize in order to build static graph representation. Currently, MCT doesn't support custom layers. We will add a more informative error for such cases.

Thanks, Elad

**Comment by reuvenperetz** [comment]
Duplicate. Will resolve with #797
