### ISSUE TITLE
example_keras_imagenet.py fails with TypeError when using representative_dataset_gen

### ISSUE THREAD

**Issue by alexander-sony** [sony/model_optimization#678]
### Issue Type

Bug

### Source

pip (model-compression-toolkit)

### MCT Version

1.8.0

### OS Platform and Distribution

Ubuntu 20.04

### Python version

3.8.10

### Describe the issue

```shell
see code in "Code to reproduce the issue"

(venv-tut-cls) $ pip list
Package                       Version
----------------------------- ---------
absl-py                       1.4.0
astunparse                    1.6.3
cachetools                    5.3.1
certifi                       2023.5.7
charset-normalizer            3.1.0
contourpy                     1.0.7
cycler                        0.11.0
dm-tree                       0.1.8
flatbuffers                   1.12
fonttools                     4.39.4
gast                          0.4.0
google-auth                   2.19.0
google-auth-oauthlib          0.4.6
google-pasta                  0.2.0
grpcio                        1.54.2
h5py                          3.8.0
idna                          3.4
imageio                       2.30.0
importlib-metadata            6.6.0
importlib-resources           5.12.0
jax                           0.4.10
joblib                        1.2.0
keras                         2.9.0
Keras-Preprocessing           1.1.2
kiwisolver                    1.4.4
lazy_loader                   0.2
libclang                      16.0.0
Markdown                      3.4.3
MarkupSafe                    2.1.2
matplotlib                    3.7.1
ml-dtypes                     0.1.0
model-compression-toolkit     1.8.0
networkx                      3.1
numpy                         1.23.5
oauthlib                      3.2.2
opencv-python                 4.7.0.72
opt-einsum                    3.3.0
packaging                     23.1
Pillow                        9.5.0
pip                           23.1.2
pkg_resources                 0.0.0
protobuf                      3.19.6
PuLP                          2.7.0
pyasn1                        0.5.0
pyasn1-modules                0.3.0
pyparsing                     3.0.9
python-dateutil               2.8.2
PyWavelets                    1.4.1
requests                      2.31.0
requests-oauthlib             1.3.1
rsa                           4.9
scikit-image                  0.20.0
scikit-learn                  1.2.2
scipy                         1.9.1
setuptools                    44.0.0
six                           1.16.0
tensorboard                   2.9.1
tensorboard-data-server       0.6.1
tensorboard-plugin-wit        1.8.1
tensorflow                    2.9.0
tensorflow-estimator          2.9.0
tensorflow-io-gcs-filesystem  0.32.0
tensorflow-model-optimization 0.7.5
termcolor                     2.3.0
threadpoolctl                 3.1.0
tifffile                      2023.4.12
tqdm                          4.65.0
typing_extensions             4.6.2
urllib3                       1.26.16
Werkzeug                      2.3.4
wheel                         0.40.0
wrapt                         1.14.1
zipp                          3.15.0
```

### Code to reproduce the issue

```shell
# snippet from example_keras_imagenet.py + some error handling
# Also had to replace 
#    mct.ptq.keras_post_training_quantization_experimental with
#    mct.core.keras.quantization_facade.keras_post_training_quantization

def get_representative_dataset():
    print('loading dataset, this may take few minutes ...')
    dataset = tf.keras.utils.image_dataset_from_directory(
        directory=TRAIN_DATASET_FOLDER,
        batch_size=BATCH_SIZE,
        image_size=[224, 224],
        shuffle=True,
        crop_to_aspect_ratio=True,
        interpolation='bilinear')
    dataset = dataset.map(lambda x, y: (dataset_preprocess_input(x, y)))

    def representative_dataset():
        for _ in range(n_iter):
            yield dataset.take(1).get_single_element()[0].numpy()

    return representative_dataset
representative_dataset_gen = get_representative_dataset()

# -----------------------------------------------------------------------------
# Model post training quantization using MCT
# -----------------------------------------------------------------------------
from keras.applications.mobilenet_v2 import MobileNetV2 
float_model = MobileNetV2()

try:
    quantized_model, quantization_info = mct.ptq.keras_post_training_quantization_experimental(
        float_model, 
        representative_dataset_gen)
except AttributeError as e:
    log(e)  # module 'model_compression_toolkit.ptq' has no attribute 'keras_post_training_quantization_experimental'
    print(f'Using mct.core.keras.quantization_facade.keras_post_training_quantization')
    quantized_model, quantization_info = mct.core.keras.quantization_facade.keras_post_training_quantization(float_model, representative_dataset_gen)
except Exception as e:
    log(e)
```

### Log output

```shell
ERROR: <class 'AttributeError'>. err_msg: module 'model_compression_toolkit.ptq' has no attribute 'keras_post_training_quantization_experimental'
Using mct.core.keras.quantization_facade.keras_post_training_quantization
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "tests/example_keras_imagenet.py", line 75, in <module>
    quantized_model, quantization_info = mct.core.keras.quantization_facade.keras_post_training_quantization(float_model, representative_dataset_gen)
  File "/home/l1000323954/Projects/imx500/Evaluations/Tutorial-classification-imx500/venv-tut-cls/lib/python3.8/site-packages/model_compression_toolkit/core/keras/quantization_facade.py", line 124, in keras_post_training_quantization
    tg, bit_widths_config = core_runner(in_model=in_model,
  File "/home/l1000323954/Projects/imx500/Evaluations/Tutorial-classification-imx500/venv-tut-cls/lib/python3.8/site-packages/model_compression_toolkit/core/runner.py", line 98, in core_runner
    tg = _prepare_model_for_quantization(graph,
  File "/home/l1000323954/Projects/imx500/Evaluations/Tutorial-classification-imx500/venv-tut-cls/lib/python3.8/site-packages/model_compression_toolkit/core/runner.py", line 352, in _prepare_model_for_quantization
    mi.infer(_data)
  File "/home/l1000323954/Projects/imx500/Evaluations/Tutorial-classification-imx500/venv-tut-cls/lib/python3.8/site-packages/model_compression_toolkit/core/common/model_collector.py", line 95, in infer
    tensor_data = self.fw_impl.run_model_inference(self.model, inputs_list)
  File "/home/l1000323954/Projects/imx500/Evaluations/Tutorial-classification-imx500/venv-tut-cls/lib/python3.8/site-packages/model_compression_toolkit/core/keras/keras_implementation.py", line 185, in run_model_inference
    return model(input_list)
  File "/home/l1000323954/Projects/imx500/Evaluations/Tutorial-classification-imx500/venv-tut-cls/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/l1000323954/Projects/imx500/Evaluations/Tutorial-classification-imx500/venv-tut-cls/lib/python3.8/site-packages/keras/engine/input_spec.py", line 213, in assert_input_compatibility
    raise TypeError(f"Inputs to a layer should be tensors. Got: {x}")
TypeError: Inputs to a layer should be tensors. Got: <generator object get_representative_dataset.<locals>.representative_dataset at 0x7f312c1840b0>
```

**Comment by alexander-sony** [comment]
Realize that I should probably use mct.ptq.keras.quantization_facade.keras_post_training_quantization_experimental(...)

**Comment by reuvenperetz** [comment]
Hi @alexander-sony,
Thanks for pointing this out. We are moving all MCT tutorials and examples to a new API aligned with the next MCT release.
In case you're using MCT by git cloning or by installing mct-nightly, it's advised that you use **mct.ptq.keras_post_training_quantization_experimental**. On the other hand, if you have installed MCT via pip, the suitable API is **mct.keras_post_training_quantization_experimental**.
Please let us know if you have any further questions.
