### ISSUE TITLE
SNC crashes on efficientnet_b0

### ISSUE THREAD

**Issue by mikeseven** [sony/model_optimization#771]
### Issue Type

Bug

### Source

source

### MCT Version

main

### OS Platform and Distribution

ubuntu 20.04

### Python version

3.10

### Describe the issue

```shell
shift negative correction crashes with efficientnet_b0 with pytorch because the tensors passed to torch.fake_quantize_affine are numpy arrays instead of torch tensors.
```

### Expected behaviour

```shell
no crash
```

### Code to reproduce the issue

```shell
download efficientnet_b0 from torchvision model hub
create typical 8b quantizer for both weights and activations, with apply SNC true.
```

**Comment by mikeseven** [comment]
Note: this is on Pytorch 2 and calibration on imagenet.

**Comment by reuvenperetz** [comment]
Hello @mikeseven,
What are you using as inputs for inference?
I reproduced your error when the inputs are numpy arrays, but it works well with torch tensors.

Can you please run this code to see if it is reproduced?
```
import torchvision
import model_compression_toolkit as mct
import numpy as np
import torch

model = torchvision.models.efficientnet_b0(pretrained=True)

def representative_data_gen():
    for i in range(1):
        yield [torch.rand(1, 3, 224, 224)]

tpc = mct.get_target_platform_capabilities('pytorch', 'default')

core_config = mct.core.CoreConfig(quantization_config=mct.core.QuantizationConfig(shift_negative_activation_correction=True))

quantized_model, quantization_info = mct.ptq.pytorch_post_training_quantization_experimental(model,
                                                                                             representative_data_gen,
                                                                                             core_config=core_config,
                                                                                             target_platform_capabilities=tpc)
outputs=quantized_model(torch.rand(1,3,224,224))

```

Best Regards

**Comment by mikeseven** [comment]
Thanks for your reply and many thanks for this great toolkit.

Here is the config I used in your code:
```python
core_config = mct.core.CoreConfig(
    quantization_config=mct.core.QuantizationConfig(
        activation_error_method=mct.core.QuantizationErrorMethod.MSE,  
        weights_error_method=mct.core.QuantizationErrorMethod.NOCLIPPING, 
        weights_per_channel_threshold=True,  # per-channel weights
        relu_bound_to_power_of_2=False,  # True may provide slightly better accuracy
        weights_bias_correction=True,  # for stats correction of bias
        weights_second_moment_correction=True,  # for stats correction of variance
        input_scaling=False,  # not supported for pytorch yet
        # z_threshold=math.inf, # z-score for outlier removal, +- 3 sigma is considered outlier, at 10, 63.909% < 65% with inf
        linear_collapsing=True,
        residual_collapsing=True,
        softmax_shift=True,
        shift_negative_activation_correction=True,  # both have no effect on pure relu models
        shift_negative_params_search=True,
    )
)
```
This crashes with `shift_negative_params_search=True`.
Here is the trace:
```python
Traceback (most recent call last):
  File "experiments/efficientnet.py", line 39, in <module>
    quantized_model, quantization_info = mct.ptq.pytorch_post_training_quantization_experimental(
  File "code/sony_model_optimization/model_compression_toolkit/ptq/pytorch/quantization_facade.py", line 109, in pytorch_post_training_quantization_experimental
    tg, bit_widths_config = core_runner(in_model=in_module,
  File "code/sony_model_optimization/model_compression_toolkit/core/runner.py", line 98, in core_runner
    tg = _prepare_model_for_quantization(graph,
  File "code/sony_model_optimization/model_compression_toolkit/core/runner.py", line 384, in _prepare_model_for_quantization
    transformed_graph = fw_impl.shift_negative_correction(transformed_graph,
  File "code/sony_model_optimization/model_compression_toolkit/core/pytorch/pytorch_implementation.py", line 195, in shift_negative_correction
    return pytorch_apply_shift_negative_correction(graph,
  File "code/sony_model_optimization/model_compression_toolkit/core/pytorch/graph_substitutions/substitutions/shift_negative_activation.py", line 209, in pytorch_apply_shift_negative_correction
    return apply_shift_negative_correction(graph,
  File "code/sony_model_optimization/model_compression_toolkit/core/common/substitutions/shift_negative_activation.py", line 512, in apply_shift_negative_correction
    graph = shift_negative_function(graph,
  File "code/sony_model_optimization/model_compression_toolkit/core/common/substitutions/shift_negative_activation.py", line 266, in shift_negative_function
    q_bins = non_linear_node_cfg_candidate.activation_quantization_fn(
  File "code/sony_model_optimization/model_compression_toolkit/core/pytorch/quantizer/fake_quant_builder.py", line 74, in <lambda>
    return lambda x: q(x, min_value, max_value, scale)
  File "code/sony_model_optimization/model_compression_toolkit/core/pytorch/quantizer/fake_quant_builder.py", line 151, in q
    return torch.fake_quantize_per_tensor_affine(x,
TypeError: fake_quantize_per_tensor_affine() received an invalid combination of arguments - got (numpy.ndarray, quant_max=int, quant_min=int, zero_point=int, scale=numpy.float64), but expected one of:
 * (Tensor input, Tensor scale, Tensor zero_point, int quant_min, int quant_max)
      didn't match because some of the arguments have invalid types: (numpy.ndarray, scale=numpy.float64, zero_point=int, quant_min=int, quant_max=int)
 * (Tensor input, float scale, int zero_point, int quant_min, int quant_max)
      didn't match because some of the arguments have invalid types: (numpy.ndarray, scale=numpy.float64, zero_point=int, quant_min=int, quant_max=int)
```

**Comment by reuvenperetz** [comment]
Hello @mikeseven,
Some fixes were merged into the main branch. Can you please retry it and see if it is reproduced?

Best Regards

**Comment by mikeseven** [comment]
I confirm it works, thanks so much!

However, there is another issue I hadn't seen before when using 'activation_quantization_method=tp.QuantizationMethod.POWER_OF_TWO`

In exporting the quantized ONNX model, it complains that the range is int16 [-32768,32767]. This comes from silu(x)=x * sigmoid(x). I resolved the issue by forcing it to be within [-128,127] by doing
```python
        swish = tp.OperatorsSet(  # noqa: F841
            "Swish",
            tp.get_default_quantization_config_options().clone_and_edit(fixed_zero_point=-128, fixed_scale=1 / 256),
        )
``` 

Is there a better way?

For efficientnet b0, the acc@1 is rather low at 47% vs fp32 77.7%, while other versions of the same model remain below 2% error. Any idea how to improve accuracy?

**Comment by reuvenperetz** [comment]
Hello @mikeseven,
I'll look into it. Please try to disable weights_second_moment_correction in the configuration for now and see if it helps.

Best Regards

**Comment by mikeseven** [comment]
it is slightly worse (-0.5%) on efficientnet b0 but much better (+2%) on efficientnet v2 s.
Looking at the graph, silu gets decomposed as x * sigmoid(x), with quantizers before and after sigmoid. I think this could be the issue.
I specified swish as:
```python
tp.OperationsSetToLayers("Swish", [nn.SiLU, F.silu, nn.Hardswish, F.hardswish])

sigmoid = tp.OperatorsSet( 
    "Sigmoid",
    tp.get_default_quantization_config_options().clone_and_edit(fixed_zero_point=-128, fixed_scale=1 / 256),
)
swish = tp.OperatorsSet( 
    "Swish",
    tp.get_default_quantization_config_options().clone_and_edit(fixed_zero_point=-128, fixed_scale=1 / 256),
)
```
Is it the correct way?
Why is SiLU lowered?
Is there a better way to specify a better quantization of such functions e.g. as a LUT?

**Comment by reuvenperetz** [comment]
Hi @mikeseven ,
Thanks for your feedback!
* For efficientnetb0, I achieved a result of 73.54 (baseline is 77.69); for efficientnet_v2_s, it's 74.66 (baseline is 84.23). This was using MCT tutorials.
It's important to note that different features might impact models differently. I'd suggest following the tutorials' default configurations where possible.
* Regarding the silu decomposition, I couldn't reproduce the issue. Based on my observations, it doesn't seem MCT quantizes the outputs of the sigmoid. Can you provide steps or more details on how you got to this issue?
* About the TPC you mentioned, according to the [documentation](https://sony.github.io/model_optimization/docs/api/experimental_api_docs/modules/target_platform.html), MCT isn't currently used in the arguments you referred to.
* If you're looking for supported quantizers to use in the TPC, you can find them [here](https://sony.github.io/model_optimization/docs/api/experimental_api_docs/modules/target_platform.html#model_compression_toolkit.target_platform.QuantizationMethod).

 

Best regards

**Comment by mikeseven** [comment]
Dear @reuvenperetz,

- I obtained similar results with the settings posted above: 72.904% for efficientnet_b0 and 77.998% for efficientnet_b2_s by disable residual collapse. That's 6% and 8% resp. lower relative difference, which is quite high compared to other torchvision classication model, typically below 1.5% except shufflenet_v2_x1_5 at 5.5%.
- Regarding silu decomposition, it still happens with a quantizer between sigmoid and mul when silu is decomposed as mul(x,sigmoid(x)). You can see that by dumping FX graph or exporting to ONNX. 
- In the documentation, I'm not sure how to use LUT options so I used a fixed sampling for silu and sigmoid. Maybe a more accurate estimation would lower the relative error? 

Anyway, different settings may work better for some models. I'm trying to figure them out.

Thanks for your help!

**Comment by reuvenperetz** [comment]
Thanks for the info!
* I'll check the residual collapse issue you mentioned.
* When using torch.nn.SiLU I don't see that the sigmoid is quantized after exporting to ONNX. However, when silu is defined manually (for example mul(x,sigmoid(x))) it happens. Do you have this issue with torchvision models? 
* For LUT, please see how it's defined [here ](https://github.com/sony/model_optimization/blob/82c2f3addfd4cbaa925085d712efab1a0263e506/model_compression_toolkit/target_platform_capabilities/tpc_models/default_tpc/v4_lut/tp_model.py#L71)(for 2 and 4 bits).

**Comment by mikeseven** [comment]
I think I found the culprit. 
```python
activations_after_conv_to_fuse = tp.OperatorSetConcat(any_relu, swish, prelu, sigmoid, tanh)
```
You are fusing conv+swish but I removed it because on embedded processors we can't fuse it, nor sigmoid nor tanh but we can with a LUT version of these operators.

Issue closed! Thanks so much for your help.
