### ISSUE TITLE
yolov8n  can not be export on imx500

### ISSUE THREAD

**Issue by yunlongwang-leopard** [sony/model_optimization#790]
### Issue Type

Bug

### Source

source

### MCT Version

1.9.0

### OS Platform and Distribution

windows 10

### Python version

3.8

### Describe the issue

```shell
yolov8n can not be export when the target platform is imx500
```

### Expected behaviour

```shell
yolov8n can work on imx500
```

### Code to reproduce the issue

```shell
python main.py --model_name yolov8n --model_library ultralytics --representative_dataset_folder ./coco128/images/train2017 --num_representative_images 64 --batch_size 1 --target_platform_name imx500
```

### Log output

```shell
from  n    params  module                                       arguments                     
  0                  -1  1       464  ultralytics.nn.modules.Conv                  [3, 16, 3, 2]                 
  1                  -1  1      4672  ultralytics.nn.modules.Conv                  [16, 32, 3, 2]                
  2                  -1  1      7360  ultralytics.nn.modules.C2f                   [32, 32, 1, True]             
  3                  -1  1     18560  ultralytics.nn.modules.Conv                  [32, 64, 3, 2]                
  4                  -1  2     49664  ultralytics.nn.modules.C2f                   [64, 64, 2, True]             
  5                  -1  1     73984  ultralytics.nn.modules.Conv                  [64, 128, 3, 2]               
  6                  -1  2    197632  ultralytics.nn.modules.C2f                   [128, 128, 2, True]           
  7                  -1  1    295424  ultralytics.nn.modules.Conv                  [128, 256, 3, 2]              
  8                  -1  1    460288  ultralytics.nn.modules.C2f                   [256, 256, 1, True]           
  9                  -1  1    164608  ultralytics.nn.modules.SPPF                  [256, 256, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.Concat                [1]                           
 12                  -1  1    148224  ultralytics.nn.modules.C2f                   [384, 128, 1]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.Concat                [1]                           
 15                  -1  1     37248  ultralytics.nn.modules.C2f                   [192, 64, 1]                  
 16                  -1  1     36992  ultralytics.nn.modules.Conv                  [64, 64, 3, 2]                
 17            [-1, 12]  1         0  ultralytics.nn.modules.Concat                [1]                           
 18                  -1  1    123648  ultralytics.nn.modules.C2f                   [192, 128, 1]                 
 19                  -1  1    147712  ultralytics.nn.modules.Conv                  [128, 128, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.Concat                [1]                           
 21                  -1  1    493056  ultralytics.nn.modules.C2f                   [384, 256, 1]                 
 22        [15, 18, 21]  1    897664  ultralytics.nn.modules.Detect                [80, [64, 128, 256]]          
Model summary: 225 layers, 3157200 parameters, 3157184 gradients, 8.9 GFLOPs

 target_platform_cap  <model_compression_toolkit.target_platform_capabilities.target_platform.targetplatform2framework.target_platform_capabilities.TargetPlatformCapabilities object at 0x0000021F72B38E80>
INFO:root:Running MCT... number of representative images: E:/project/python/work/box_counting/git_code/yolov5/datasets/coco128/images/train2017, number of calibration iters: 64
Scanning E:\project\python\work\box_counting\git_code\yolov5\datasets\coco128\labels\train2017.cache... 128 images, 2 backgrounds, 0 corrupt: 100%|██████████| 128/128 [00:00<?, ?it/s]
INFO:root:Start Model Reading...
Pytorch model has a parameter or constant Tensor value. This can cause unexpected behaviour when converting the model.
Pytorch model has a parameter or constant Tensor value. This can cause unexpected behaviour when converting the model.
WARNING:Constrained Model Optimization:Pytorch model has a parameter or constant Tensor value. This can cause unexpected behaviour when converting the model.
WARNING:Constrained Model Optimization:Pytorch model has a parameter or constant Tensor value. This can cause unexpected behaviour when converting the model.
64it [00:32,  1.96it/s]
F:\project\model_optimization\model_compression_toolkit\core\common\mixed_precision\kpi_tools\kpi_methods.py:291: RuntimeWarning: overflow encountered in long_scalars
  node_bops = node_weights_nbits * input_activation_nbits * node_mac
F:\project\model_optimization\model_compression_toolkit\core\pytorch\pytorch_implementation.py:491: RuntimeWarning: overflow encountered in long_scalars
  return np.prod([x for x in output_shape if x is not None]) * \
F:\project\model_optimization\model_compression_toolkit\core\common\mixed_precision\kpi_tools\kpi_aggregation_methods.py:37: RuntimeWarning: overflow encountered in long_scalars
  return [0] if len(kpi_vector) == 0 else [sum(kpi_vector)]
Using new experimental wrapped and ready for export models. To disable it, please set new_experimental_exporter to False when calling pytorch_post_training_quantization_experimental. If you encounter an issue please file a bug.
WARNING:Constrained Model Optimization:Using new experimental wrapped and ready for export models. To disable it, please set new_experimental_exporter to False when calling pytorch_post_training_quantization_experimental. If you encounter an issue please file a bug.
INFO:Constrained Model Optimization:Exporting PyTorch fake quant onnx model: F:\temp\temp\tmpa4tnphc4.onnx
Exporting PyTorch fake quant onnx model: F:\temp\temp\tmpa4tnphc4.onnx
============== Diagnostic Run torch.onnx.export version 2.0.1+cpu ==============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Traceback (most recent call last):
  File "F:/project/model_optimization/tutorials/quick_start/main.py", line 134, in <module>
    float_acc, quant_acc, quant_info, dataset_info = quantization_flow(config)
  File "F:/project/model_optimization/tutorials/quick_start/main.py", line 108, in quantization_flow
    quantized_model, quantization_info = quant.quantize(float_model,
  File "F:\project\model_optimization\tutorials\quick_start\pytorch_fw\quant.py", line 140, in quantize
    mct.exporter.pytorch_export_model(model=quantized_model, save_model_path=onnx_file_path,
  File "F:\project\model_optimization\model_compression_toolkit\exporter\model_exporter\pytorch\pytorch_export_facade.py", line 99, in pytorch_export_model
    exporter.export()
  File "F:\project\model_optimization\model_compression_toolkit\exporter\model_exporter\pytorch\fakely_quant_onnx_pytorch_exporter.py", line 95, in export
    torch.onnx.export(self.model,
  File "H:\development\conda\envs\imx500\lib\site-packages\torch\onnx\utils.py", line 506, in export
    _export(
  File "H:\development\conda\envs\imx500\lib\site-packages\torch\onnx\utils.py", line 1548, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "H:\development\conda\envs\imx500\lib\site-packages\torch\onnx\utils.py", line 1117, in _model_to_graph
    graph = _optimize_graph(
  File "H:\development\conda\envs\imx500\lib\site-packages\torch\onnx\utils.py", line 665, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "H:\development\conda\envs\imx500\lib\site-packages\torch\onnx\utils.py", line 1891, in _run_symbolic_function
    return symbolic_fn(graph_context, *inputs, **attrs)
  File "H:\development\conda\envs\imx500\lib\site-packages\torch\onnx\symbolic_helper.py", line 306, in wrapper
    return fn(g, *args, **kwargs)
  File "H:\development\conda\envs\imx500\lib\site-packages\torch\onnx\symbolic_opset13.py", line 385, in fake_quantize_per_tensor_affine
    raise errors.SymbolicValueError(
torch.onnx.errors.SymbolicValueError: For (quant_min, quant_max), ONNX allows only (0, 127), (0, 255) and (-128, 127). Got (-32768, 32767)  [Caused by the value '144 defined in (%144 : Float(*, 16, 320, 320, strides=[1638400, 102400, 320, 1], requires_grad=1, device=cpu) = onnx::Mul(%input.3, %143), scope: model_compression_toolkit.core.pytorch.back2framework.pytorch_model_builder.PytorchModel::/torch.nn.modules.activation.SiLU::model_0_act # H:\development\conda\envs\imx500\lib\site-packages\torch\nn\functional.py:2058:0
)' (type 'Tensor') in the TorchScript graph. The containing node has kind 'onnx::Mul'.] 
    (node defined in H:\development\conda\envs\imx500\lib\site-packages\torch\nn\functional.py(2058): silu
H:\development\conda\envs\imx500\lib\site-packages\torch\nn\modules\activation.py(396): forward
H:\development\conda\envs\imx500\lib\site-packages\torch\nn\modules\module.py(1488): _slow_forward
H:\development\conda\envs\imx500\lib\site-packages\torch\nn\modules\module.py(1501): _call_impl
F:\project\model_optimization\model_compression_toolkit\core\pytorch\back2framework\pytorch_model_builder.py(93): _run_operation
F:\project\model_optimization\model_compression_toolkit\core\pytorch\back2framework\pytorch_model_builder.py(267): forward
H:\development\conda\envs\imx500\lib\site-packages\torch\nn\modules\module.py(1488): _slow_forward
H:\development\conda\envs\imx500\lib\site-packages\torch\nn\modules\module.py(1501): _call_impl
H:\development\conda\envs\imx500\lib\site-packages\torch\jit\_trace.py(118): wrapper
H:\development\conda\envs\imx500\lib\site-packages\torch\jit\_trace.py(127): forward
H:\development\conda\envs\imx500\lib\site-packages\torch\nn\modules\module.py(1501): _call_impl
H:\development\conda\envs\imx500\lib\site-packages\torch\jit\_trace.py(1268): _get_trace_graph
H:\development\conda\envs\imx500\lib\site-packages\torch\onnx\utils.py(893): _trace_and_get_graph_from_model
H:\development\conda\envs\imx500\lib\site-packages\torch\onnx\utils.py(989): _create_jit_graph
H:\development\conda\envs\imx500\lib\site-packages\torch\onnx\utils.py(1113): _model_to_graph
H:\development\conda\envs\imx500\lib\site-packages\torch\onnx\utils.py(1548): _export
H:\development\conda\envs\imx500\lib\site-packages\torch\onnx\utils.py(506): export
F:\project\model_optimization\model_compression_toolkit\exporter\model_exporter\pytorch\fakely_quant_onnx_pytorch_exporter.py(95): export
F:\project\model_optimization\model_compression_toolkit\exporter\model_exporter\pytorch\pytorch_export_facade.py(99): pytorch_export_model
F:\project\model_optimization\tutorials\quick_start\pytorch_fw\quant.py(140): quantize
F:/project/model_optimization/tutorials/quick_start/main.py(108): quantization_flow
F:/project/model_optimization/tutorials/quick_start/main.py(134): <module>
)

    Inputs:
        #0: input.3 defined in (%input.3 : Float(*, 16, 320, 320, strides=[1638400, 102400, 320, 1], requires_grad=0, device=cpu) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[2, 2]](%input, %model_0_conv_bn.weight, %model_0_conv_bn.bias), scope: model_compression_toolkit.core.pytorch.back2framework.pytorch_model_builder.PytorchModel::/torch.nn.modules.conv.Conv2d::model_0_conv_bn # H:\development\conda\envs\imx500\lib\site-packages\torch\nn\modules\conv.py:459:0
    )  (type 'Tensor')
        #1: 143 defined in (%143 : Float(*, 16, 320, 320, device=cpu) = onnx::Sigmoid(%input.3), scope: model_compression_toolkit.core.pytorch.back2framework.pytorch_model_builder.PytorchModel::/torch.nn.modules.activation.SiLU::model_0_act # H:\development\conda\envs\imx500\lib\site-packages\torch\nn\functional.py:2058:0
    )  (type 'Tensor')
    Outputs:
        #0: 144 defined in (%144 : Float(*, 16, 320, 320, strides=[1638400, 102400, 320, 1], requires_grad=1, device=cpu) = onnx::Mul(%input.3, %143), scope: model_compression_toolkit.core.pytorch.back2framework.pytorch_model_builder.PytorchModel::/torch.nn.modules.activation.SiLU::model_0_act # H:\development\conda\envs\imx500\lib\site-packages\torch\nn\functional.py:2058:0
    )  (type 'Tensor')

Process finished with exit code 1
```

**Comment by reuvenperetz** [comment]
Hi @yunlongwang-leopard,

Thank you for bringing this issue to our attention.
Currently, exporting models to ONNX is not supported for models with 16-bit quantization (please see [here](https://onnx.ai/onnx/operators/onnx__QuantizeLinear.html#l-onnx-doc-quantizelinear)). Thus, enabling shift-negative correction in MCT prevents the ONNX export. We're working on a solution, but in the meantime, you can disable the shift-negative correction to allow exporting it if needed.

Best Regards.

**Comment by yunlongwang-leopard** [comment]
Hi @reuvenperetz  

Thanks for your reply. 
I can get files in onnx format, but since imx500 only supports tflite and input format is uint8, so how to do that?

thanks

**Comment by ServiAmirPM** [comment]
Hi @yunlongwang-leopard 

MCT outputs a framework-based quantized (or fakely quantized) model, and in order to take it to Sony IMX500, you should utilize IMX500 converter tool (as appears in the [Sony developer portal](https://developer.sony.com/imx500))

**Comment by yunlongwang-leopard** [comment]
yes I know that.

Because IMX500 converter tool only supports tflite file, for now , I only can get onnx file.

so I need to convert the onnx file to tflite with sony library

**Comment by ServiAmirPM** [comment]
_*As this is an issue that's not related to MCT - please contact me directly at amir.servi@sony.com for further clarifications_ 

Starting version 3.5, IMX500 converter supports both TFLite and PyTorch (via ONNX).
Instead of using ConvPy, you should use [Uni-PyTorch](https://developer.sony.com/imx500/developer-tools/documentation/sdsp-neural-network-converter-manual/?version=v3.7&progLang=#uni-pytorch)

uni-pytorch is the component of the SDSP neural network converter that converts a trained deep neural network (DNN) model from .Onnx format to the uni (universal neural-network interface) format.

Note that PyTorch is the only supported source for ONNX serialization in this version (you can't have a TensorFlow-based ONNX model as an input to uni-PyTorch).

I hope it's clear. Let me know if that helped.

**Comment by yunlongwang-leopard** [comment]
for yolov8n, Can you update a more clear documents.

I am not clear how to run it successfully with imx500

thanks

**Comment by haihabi** [comment]
Not relevant to MCT
