### ISSUE TITLE
YOLO v5 model is NOT forwards compatible with YOLOv8

### ISSUE THREAD

**Issue by Ming-Ivy** [sony/model_optimization#896]
### Issue Type

Performance

### Source

source

### MCT Version

1.10.0

### Describe the issue

```shell
When I try to use yolov5 on MCT with command:python main.py --model_name yolov5.pt --model_library ultralytics --representative_dataset_folder /datasets/coco/images/train2017 --num_representative_images 64 --batch_size 1, 

It appears error:

TypeError: ERROR  C:/WorkMing/02_liangzi/model_changing/best.pt appears to be an Ultralytics YOLOv5 model originally trained with https://github.com/ultralytics/yolov5.
This model is NOT forwards compatible with YOLOv8 at https://github.com/ultralytics/ultralytics.
Recommend fixes are to train a new model using the latest 'ultralytics' package or to run a command with an official YOLOv8 model, i.e. 'yolo predict model=yolov8n.pt'

I find out that there are dictionary in library_mapping.py, with ultralytics_lib in it. is it necessary to self create a folder with yolov5?
```

### Expected behaviour

```shell
So I wondering how can I successfully run yolov5 in this MCT project? Please.
```

### Code to reproduce the issue

```shell
python main.py --model_name yolov5s.pt --model_library ultralytics --representative_dataset_folder /datasets/coco/images/train2017 --num_representative_images 64 --batch_size 1


  File "C:\Users\0107409441\AppData\Local\Programs\Python\Python38\lib\site-packages\ultralytics\nn\tasks.py", line 344, in torch_safe_load
    raise TypeError(
TypeError: ERROR  C:/WorkMing/02_liangzi/model_changing/best.pt appears to be an Ultralytics YOLOv5 model originally trained with https://github.com/ultralytics/yolov5.
This model is NOT forwards compatible with YOLOv8 at https://github.com/ultralytics/ultralytics.
Recommend fixes are to train a new model using the latest 'ultralytics' package or to run a command with an official YOLOv8 model, i.e. 'yolo predict model=yolov8n.pt'

 python main.py --model_name yolov5s.pt --model_library yolov5 --representative_dataset_folder /datasets/coco/images/train2017 --num_representative_images 64 --batch_size 1

  File "C:\Users\0107409441\AppData\Local\Programs\Python\Python38\lib\site-packages\yolov5\utils\general.py", line 39, in <module>
    from ultralytics.utils.checks import check_requirements
ModuleNotFoundError: No module named 'ultralytics.utils'

Import yolov5

PS C:\WorkMing\02_liangzi\model_optimization\tutorials\quick_start> python main.py  --model_library yolov5 --representative_dataset_folder C:/WorkMing/02_liangzi/coco_person/images/train --num_representative_images 64 --batch_size 1
WARNING ⚠️ Ultralytics settings reset to default values. This may be due to a possible problem with your settings or a recent ultralytics package up
date.
View settings with 'yolo settings' or at 'C:\Users\0107409441\AppData\Roaming\Ultralytics\settings.yaml'
Update settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'.
Traceback (most recent call last):
  File "main.py", line 131, in <module>
    float_acc, quant_acc, quant_info, dataset_info = quantization_flow(config)
  File "main.py", line 88, in quantization_flow
    model_lib_module, quant_module = find_modules(config[MODEL_LIBRARY])
  File "C:\WorkMing\02_liangzi\model_optimization\tutorials\quick_start\common\library_mapping.py", line 44, in find_modules
    folder_name = LIB2FOLDER_DICT[lib]
KeyError: 'yolov5'
```

**Comment by Idan-BenAmi** [comment]
Hi @Ming-Ivy,
Thank you for your feedback.
Currently, our quick start project only supports YOLOv8 models from Ultralytics. Integrating YOLOv5 would require modifications and additional support in the Ultralytics "model_lib" module. We will consider adding support for it in the future and be glad to update you of any developments in this regard.
Feel free to reach out if you have any further questions.
Thanks
Idan

**Comment by ofirgo** [comment]
Since there haven't been any recent updates or responses, I'm closing this thread. If you encounter any further issues or have additional questions regarding this model, please feel free to reopen the issue.
